pipeline {
  agent any
  environment {
    XYGENI_TOKEN = credentials('XYGENI_TOKEN')
    PROJECT_NAME="Jenkins1"
    PROJECT_HOME="/var/lib/jenkins/workspace/XyTest1/JavaVulnerableLab"
  }
  stages {
    stage('Install Xygeni scanner') {
      steps {
        sh """
        date
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
        curl -L https://get.xygeni.io/latest/scanner/install.sh | \
        /bin/bash -s -- -t $XYGENI_TOKEN -d $WORKSPACE/scanner
        ls -l
        date
        """
      }
    }
    stage('Scan for issues') {
      steps {
        sh """
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
        $WORKSPACE/scanner/xygeni scan \
          -n $PROJECT_NAME \
          --dir $PROJECT_HOME
        """
      }
    }
  }
}